import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Token Image List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen w-full flex-col flex justify-center items-center">
        <h1 className="text-5xl font-bold"><span className="text-blue-600">Diverse</span> Token Image</h1>
        <p className="mt-4 text-xl font-light">Public Server For Token Images</p>
      </main>

    </div>
  )
}
